
package ajs.x;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AJSPort", targetNamespace = "urn:X-AJS")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AJSPort {


    /**
     * 
     * @param pridajCvicenieRequestPart
     * @return
     *     returns ajs.x.PridajCvicenieResponse
     * @throws DuplicitnyZaznam_Exception
     */
    @WebMethod(action = "urn:X-AJS/pridajCvicenie")
    @WebResult(name = "pridajCvicenieResponse", targetNamespace = "urn:X-AJS", partName = "pridajCvicenieResponsePart")
    public PridajCvicenieResponse pridajCvicenie(
        @WebParam(name = "pridajCvicenieRequest", targetNamespace = "urn:X-AJS", partName = "pridajCvicenieRequestPart")
        PridajCvicenieRequest pridajCvicenieRequestPart)
        throws DuplicitnyZaznam_Exception
    ;

}
