
package ajs.x;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "duplicitnyZaznam", targetNamespace = "urn:X-AJS")
public class DuplicitnyZaznam_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private DuplicitnyZaznam faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public DuplicitnyZaznam_Exception(String message, DuplicitnyZaznam faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public DuplicitnyZaznam_Exception(String message, DuplicitnyZaznam faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: ajs.x.DuplicitnyZaznam
     */
    public DuplicitnyZaznam getFaultInfo() {
        return faultInfo;
    }

}
